version: '3.2'
services:

  DB:
    image: postgis/postgis:14-master
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
      - 5433:5433
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/
    networks:
      - OfoghTest

networks:
  OfoghTest:
    driver: bridge
