# Generated by Django 4.0.4 on 2022-05-15 19:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('width', models.FloatField(verbose_name='Road Length')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TollStation',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('toll_per_cross', models.IntegerField(verbose_name='Toll Price per car cross')),
                ('location', django.contrib.gis.db.models.fields.PointField(primary_key=True, serialize=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Of passage')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road')),
            ],
        ),
    ]
