# Generated by Django 4.0.4 on 2022-05-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
