# Generated by Django 4.0.4 on 2022-05-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_delete_travel'),
        ('cars', '0003_alter_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Of passage')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='roads_traveled',
            field=models.ManyToManyField(related_name='traveled', related_query_name='travel', through='cars.Travel', to='road.road'),
        ),
        migrations.AddField(
            model_name='travel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AddField(
            model_name='travel',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.road'),
        ),
    ]
