# Generated by Django 4.0.4 on 2022-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_delete_travel'),
        ('cars', '0005_alter_car_roads_traveled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='roads_traveled',
            field=models.ManyToManyField(related_name='Traveled', related_query_name='RoadTravel', through='cars.Travel', to='road.road'),
        ),
    ]
