# Generated by Django 4.0.4 on 2022-05-16 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_roads_traveled'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(auto_created=True, null=True, srid=4326, verbose_name='Current location of the car'),
        ),
        migrations.AddField(
            model_name='car',
            name='last_update_location',
            field=models.DateTimeField(null=True),
        ),
    ]
